#!/bin/bash

# LOGIN TEST GUIDE

echo "============================================"
echo "  FINPULSE LOGIN TEST GUIDE"
echo "============================================"
echo ""
echo "The dev server is running on http://localhost:3000"
echo ""
echo "STEP 1: Test the login endpoint (API)"
echo "-------"
echo "Run this command:"
echo ""
echo 'curl -X POST http://localhost:3000/api/login \'
echo '  -H "Content-Type: application/json" \'
echo '  -d '"'"'{"email":"pavanreddy@intellicar.in","password":"Test@123"}'"'"''
echo ""
echo "Expected response: JSON with success:true and token"
echo ""
echo "STEP 2: Test login in browser"
echo "-------"
echo "1. Open http://localhost:3000/login in your browser"
echo "2. Enter email: pavanreddy@intellicar.in"
echo "3. Enter password: Test@123"
echo "4. Click 'Sign In' button"
echo ""
echo "Expected behavior:"
echo "- Page should show 'Signing in...' while submitting"
echo "- After successful login, page should redirect to dashboard (/)"
echo "- You should see the dashboard with tasks"
echo ""
echo "STEP 3: Check browser console for debug logs"
echo "-------"
echo "Press F12 to open developer console"
echo "Look for messages starting with [v0]"
echo "This will show you the login flow in detail"
echo ""
echo "STEP 4: Test auth status"
echo "-------"
echo "Run this command to check if auth is working:"
echo ""
echo 'curl http://localhost:3000/api/auth/status'
echo ""
echo "Should return: { authenticated: true, user: {...} }"
echo ""
echo "============================================"
echo ""
echo "SERVER IS RUNNING: http://localhost:3000"
echo "LOGIN PAGE: http://localhost:3000/login"
echo "CREDENTIALS:"
echo "  Email: pavanreddy@intellicar.in"
echo "  Password: Test@123"
echo ""
echo "============================================"
