import ExcelJS from 'exceljs';
import { saveAs } from 'file-saver';
import { BRAND_COLORS, BRAND_TEXT } from './reportAssets';

/**
 * Professional Excel Report Generator
 * Creates a multi-sheet workbook with branding and executive summary.
 */
export async function generateProfessionalExcelReport(data: {
  tasks: any[];
  idrs: any[];
  los: any[];
  analytics: any;
  filters: { entity: string; dept: string; user: string };
  generatedBy: string;
}, mode: 'download' | 'buffer' = 'download') {
  const workbook = new ExcelJS.Workbook();
  workbook.creator = BRAND_TEXT.PRODUCT_NAME;
  workbook.lastModifiedBy = data.generatedBy;
  workbook.created = new Date();

  // 1. DASHBOARD SHEET
  const dashSheet = workbook.addWorksheet('Executive Summary');
  
  // Header Branding
  dashSheet.mergeCells('A1:E1');
  const headerCell = dashSheet.getCell('A1');
  headerCell.value = `${BRAND_TEXT.PRODUCT_NAME.toUpperCase()} - ANALYTICS`;
  headerCell.font = { name: 'Arial', size: 20, bold: true, color: { argb: BRAND_COLORS.INTELLICAR_BLUE.replace('#', '') } };
  headerCell.alignment = { horizontal: 'center', vertical: 'middle' };

  dashSheet.mergeCells('A2:E2');
  const subHeaderCell = dashSheet.getCell('A2');
  subHeaderCell.value = BRAND_TEXT.CORPORATE_NAME;
  subHeaderCell.font = { name: 'Arial', size: 12, italic: true, color: { argb: BRAND_COLORS.MUTED.replace('#', '') } };
  subHeaderCell.alignment = { horizontal: 'center' };

  // Report Info
  dashSheet.addRow([]);
  const metaHeader = dashSheet.addRow(['REPORT METADATA']);
  metaHeader.font = { bold: true };
  
  dashSheet.addRow(['Generated On', new Date().toLocaleString()]);
  dashSheet.addRow(['Generated By', data.generatedBy]);
  dashSheet.addRow(['Applied Filters', `Entity: ${data.filters.entity} | Dept: ${data.filters.dept} | User: ${data.filters.user}`]);
  
  dashSheet.addRow([]);
  
  // KPI Cards Section
  const kpiTitleRow = dashSheet.addRow(['KEY PERFORMANCE INDICATORS']);
  kpiTitleRow.font = { bold: true, size: 14, color: { argb: BRAND_COLORS.DARK.replace('#', '') } };
  
  const kpiRow = dashSheet.addRow(['Total Tasks', 'On-Time Rate', 'Overdue', 'Late Completions', 'LO Count']);
  kpiRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
  kpiRow.eachCell(cell => {
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_COLORS.INTELLICAR_BLUE.replace('#', '') } };
  });

  const kpiValues = dashSheet.addRow([
    data.analytics.totalTasks,
    (data.analytics.totalTasks > 0 ? Math.round((data.analytics.onTimeTasks / data.analytics.totalTasks) * 100) : 0) + '%',
    data.analytics.overdueTasks,
    data.analytics.lateTasks,
    data.los.length
  ]);
  kpiValues.font = { size: 12, bold: true };
  kpiValues.alignment = { horizontal: 'center' };

  // Adjust Columns
  dashSheet.getColumn(1).width = 25;
  dashSheet.getColumn(2).width = 20;
  dashSheet.getColumn(3).width = 20;
  dashSheet.getColumn(4).width = 20;
  dashSheet.getColumn(5).width = 20;

  // 2. DETAILED TASKS SHEET
  const taskSheet = workbook.addWorksheet('Task Details');
  taskSheet.columns = [
    { header: 'ID', key: 'id', width: 10 },
    { header: 'Task Name', key: 'taskName', width: 40 },
    { header: 'Entity', key: 'entityName', width: 25 },
    { header: 'Dept', key: 'departmentName', width: 15 },
    { header: 'Owner', key: 'ownerName', width: 20 },
    { header: 'Due Date', key: 'dueDate', width: 15 },
    { header: 'Status', key: 'taskStatus', width: 15 },
    { header: 'Review', key: 'reviewStatus', width: 20 }
  ];

  // Add Data
  data.tasks.forEach(t => {
    const row = taskSheet.addRow({
      id: t.id,
      taskName: t.taskName,
      entityName: t.entityName,
      departmentName: t.departmentName,
      ownerName: t.ownerName,
      dueDate: t.dueDate ? new Date(t.dueDate).toLocaleDateString() : 'N/A',
      taskStatus: t.taskStatus,
      reviewStatus: t.reviewStatus
    });

    // Conditional Styling
    if (t.taskStatus === 'Completed') {
      row.getCell('taskStatus').font = { color: { argb: BRAND_COLORS.SUCCESS.replace('#', '') }, bold: true };
    } else if (t.dueDate && new Date(t.dueDate) < new Date() && t.taskStatus !== 'Completed') {
      row.getCell('taskStatus').font = { color: { argb: BRAND_COLORS.DANGER.replace('#', '') }, bold: true };
    }
  });

  // Header Styling
  taskSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  taskSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_COLORS.INTELLICAR_BLUE.replace('#', '') } };

  // 3. IDR PIPELINE
  const idrSheet = workbook.addWorksheet('IDR Pipeline');
  idrSheet.columns = [
    { header: 'ID', key: 'id', width: 10 },
    { header: 'Requester', key: 'requestFrom', width: 30 },
    { header: 'Nature of Request', key: 'natureOfRequest', width: 45 },
    { header: 'Status', key: 'status', width: 20 },
    { header: 'Converted Task', key: 'tid', width: 20 }
  ];
  data.idrs.forEach(r => {
    idrSheet.addRow({
      id: r.id,
      requestFrom: r.requestFrom,
      natureOfRequest: r.natureOfRequest,
      status: r.status,
      tid: r.convertedTaskId || 'Pending'
    });
  });
  idrSheet.getRow(1).font = { bold: true, color: { argb: 'FFFFFFFF' } };
  idrSheet.getRow(1).fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: BRAND_COLORS.FINPULSE_BLUE.replace('#', '') } };

  // Finalize
  const buffer = await workbook.xlsx.writeBuffer();
  if (mode === 'download') {
    saveAs(new Blob([buffer]), `FinPulse_Analytics_Report_${new Date().getTime()}.xlsx`);
  }
  return buffer;
}

