import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { BRAND_COLORS, BRAND_TEXT } from './reportAssets';

/**
 * Professional PDF Report Generator
 */
export async function generateProfessionalPDFReport(data: {
  tasks: any[];
  analytics: any;
  filters: { entity: string; dept: string; user: string };
  generatedBy: string;
}, mode: 'download' | 'buffer' = 'download') {
  const doc = new jsPDF();
  const pageHeight = doc.internal.pageSize.height;
  const pageWidth = doc.internal.pageSize.width;

  // --- HELPER: FOOTER ---
  const addFooter = (doc: jsPDF) => {
    const pageCount = (doc as any).internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(BRAND_TEXT.CONFIDENTIAL_NOTICE, 14, pageHeight - 10);
      doc.text(`Page ${i} of ${pageCount}`, pageWidth - 30, pageHeight - 10);
      doc.text(BRAND_TEXT.COPYRIGHT, pageWidth / 2, pageHeight - 10, { align: 'center' });
    }
  };

  // --- 1. COVER PAGE ---
  doc.setFillColor(BRAND_COLORS.DARK);
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text(BRAND_TEXT.PRODUCT_NAME, 14, 25);
  
  doc.setFontSize(10);
  doc.text(BRAND_TEXT.DIVISION, pageWidth - 14, 25, { align: 'right' });

  // Body Content
  doc.setTextColor(0);
  doc.setFontSize(30);
  doc.text('Performance Analytics', 14, 70);
  doc.text('Report', 14, 85);

  doc.setDrawColor(BRAND_COLORS.INTELLICAR_BLUE);
  doc.setLineWidth(2);
  doc.line(14, 95, 60, 95);

  doc.setFontSize(12);
  doc.text(`Generated For: ${data.filters.dept} Department`, 14, 115);
  doc.text(`Reporting Entity: ${data.filters.entity}`, 14, 122);
  doc.text(`User Scope: ${data.filters.user}`, 14, 129);
  
  doc.setTextColor(100);
  doc.text(`Generated By: ${data.generatedBy}`, 14, 150);
  doc.text(`Date: ${new Date().toLocaleString()}`, 14, 157);

  doc.addPage();

  // --- 2. EXECUTIVE SUMMARY ---
  doc.setTextColor(BRAND_COLORS.INTELLICAR_BLUE);
  doc.setFontSize(18);
  doc.text('Executive Summary', 14, 20);

  autoTable(doc, {
    startY: 30,
    head: [['Metric', 'Result', 'Context']],
    body: [
      ['Total Tasks Analyzed', data.analytics.totalTasks, 'Across selected scope'],
      ['Overall On-Time Rate', (data.analytics.totalTasks > 0 ? Math.round((data.analytics.onTimeTasks / data.analytics.totalTasks) * 100) : 0) + '%', 'Success Benchmark: 85%'],
      ['Active Overdue Tasks', data.analytics.overdueTasks, 'Requires immediate attention'],
      ['Historical Late Closures', data.analytics.lateTasks, 'Impacts team efficiency']
    ],
    theme: 'striped',
    headStyles: { fillColor: BRAND_COLORS.INTELLICAR_BLUE }
  });

  // --- 3. DETAILED PERFORMANCE TABLE ---
  doc.text('Task Inventory Details', 14, (doc as any).lastAutoTable.finalY + 20);
  
  autoTable(doc, {
    startY: (doc as any).lastAutoTable.finalY + 25,
    head: [['Task Name', 'Entity', 'Due Date', 'Status']],
    body: data.tasks.slice(0, 50).map(t => [
      t.taskName,
      t.entityName,
      t.dueDate ? new Date(t.dueDate).toLocaleDateString() : 'N/A',
      t.taskStatus
    ]),
    styles: { fontSize: 9 },
    headStyles: { fillColor: BRAND_COLORS.DARK },
    alternateRowStyles: { fillColor: [245, 247, 250] }
  });

  addFooter(doc);
  if (mode === 'download') {
    doc.save(`FinPulse_Analytics_Report_${new Date().getTime()}.pdf`);
  }
  return doc.output('arraybuffer');
}
